CREATE TABLE IF NOT EXISTS videos (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  s3_key VARCHAR(255) NOT NULL,
  s3_url TEXT,
  creatomate_url TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
